---

- name: Disable SELinux
  selinux: state=disabled

- name: Update Yum
  yum: name=* state=latest

- name: Install basic packages (curl, wget, etc.)
  yum: pkg={{ item }} state=latest
  with_items:
    - curl
    - gcc
    - kernel-devel
    - libzip
    - man
    - postfix
    - unzip
    - vim
    - wget

- name: Install extra packages (nano, tree, etc.)
  yum: pkg={{ item }} state=latest
  with_items:
    - nano
    - tree
